module.exports = (sequelize,DataTypes)=>{
	return sequelize.define('user',{
		id:{
			type:DataTypes.UUID,
			primaryKey:true,
			defaultValue:DataTypes.UUIDV4
		},
		username:{
			type:DataTypes.STRING(30),
			unique:true
		},
		email:{
			type:DataTypes.STRING(45),
			unique:true,
			validate:{
				isEmail:true
			}
		},
		telephone:{
			type:DataTypes.STRING(25),
			unique:true
		},
		password:{
			type:DataTypes.STRING(128),
			allowNull:false
		},
		token:{
			type:DataTypes.STRING(128),
			defaultValue:DataTypes.UUIDV4

		},
		token_generate_time:DataTypes.DATE,
		token_expired_time:DataTypes.DATE,
		last_active_time:DataTypes.DATE
	},{
		paranoid:true,
		defaultScope:{
			attributes:{
				exclude:['password']
			}
		}
	});
}
